version: '3'

services:

  db:
    env_file: web_db.env
    image: postgres:12
    volumes:
      - ./src/tmp/postgres_data:/var/lib/postgresql/data
    
  web: &web
    env_file: web_db.env
    build: .
    command: bash -c "rm -f ./src/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    
  webpacker:
    <<: *web
    env_file: webpacker.env
    command: bundle exec ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    depends_on:
      - web
    stdin_open: false
    tty: false