version: '3'

services:

  db:
    env_file: web_db.env
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  web:
    env_file: web_db.env
    build: .
    # command: bash -c "rm -f ./src/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    
volumes:
  postgres_data:
    driver: local
  