version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    working_directory: ~/intern/src
    # 実際やるjobsの内容
    steps:
      - checkout:
          path: ~/intern
      - ruby/install-deps
      # ↑bundle installのようなもの
      
  test:
    docker:
      - image: circleci/ruby:2.7.3
      # - image: circleci/postgres:12
      #   environment:
      #     POSTGRES_PASSWORD: "password"
      #     POSTGRES_DATABASE: "myapp_test"
      #     POSTGRES_USER: "admin"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/intern/src
    steps:
      - checkout:
          path: ~/intern/src
      # - ruby/install-deps
      # - run:
      #     name: Database setup
      #     command: bundle exec rails db:migrate
      - run:
          name: test
          command: docker-compose run --rm web rspec -f documentation

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build